### ISSUE TITLE
Publish helm chart

### ISSUE THREAD

**Issue by LancelotMarti** [dscc-admin-ch/vllm#5]
Steps

* Create GitHub action to publish code on repo dsccadminch/helm-charts
   * Check publish_charts.yml on Lomas for template
   * Need to create SECRET TOKEN
   * Repo need to be public to use github action

**Comment by Jono711** [comment]
- created SECRET TOKEN

**Comment by Jono711** [comment]
- Created release/v0.0.1 branch

**Comment by Jono711** [comment]
Helm error:

Run cpina/github-action-push-to-another-repository@main
/usr/bin/docker run --name bc779aa8f9bc6622745398fc78106e18de75c_94e85a --label 8bc779 --workdir /github/workspace --rm -e "SSH_DEPLOY_KEY" -e "INPUT_SOURCE-DIRECTORY" -e "INPUT_DESTINATION-GITHUB-USERNAME" -e "INPUT_DESTINATION-REPOSITORY-NAME" -e "INPUT_TARGET-BRANCH" -e "INPUT_TARGET-DIRECTORY" -e "INPUT_SOURCE-BEFORE-DIRECTORY" -e "INPUT_USER-EMAIL" -e "INPUT_GITHUB-SERVER" -e "INPUT_USER-NAME" -e "INPUT_DESTINATION-REPOSITORY-USERNAME" -e "INPUT_COMMIT-MESSAGE" -e "INPUT_CREATE-TARGET-BRANCH-IF-NEEDED" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/vllm/vllm":"/github/workspace" 8bc779:aa8f9bc6622745398fc78106e18de75c  "" "deployment/helm/charts/vllm-gpu" "dscc-admin-ch" "helm-charts" "github.com" "" "" "" "master" "Update from ORIGIN_COMMIT" "charts/vllm-gpu" "false"
[+] Action start
[+] Using SSH_DEPLOY_KEY
# github.com:22 SSH-2.0-babeld-0c1de7cd8
# github.com:22 SSH-2.0-babeld-0c1de7cd8
# github.com:22 SSH-2.0-babeld-0c1de7cd8
# github.com:22 SSH-2.0-babeld-0c1de7cd8
# github.com:22 SSH-2.0-babeld-0c1de7cd8
[+] Git version
git version 2.45.2
[+] Enable git lfs
Git LFS initialized.
[+] Cloning destination git repository helm-charts
Cloning into '/tmp/tmp.OoGBBe'...
Load key "/github/home/.ssh/deploy_key": error in libcrypto
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Could not clone the destination repository. Command:
Error: git clone --single-branch --branch master git@github.com:dscc-admin-ch/helm-charts.git /tmp/tmp.OoGBBe
Error: (Note that if they exist USER_NAME and API_TOKEN is redacted by GitHub)
Error: Please verify that the target repository exist AND that it contains the destination branch name, and is accesible by the API_TOKEN_GITHUB OR SSH_DEPLOY_KEY

**Comment by Jono711** [comment]
investigate this: https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey
