### ISSUE TITLE
Create helm chart specific to onyxia

### ISSUE THREAD

**Issue by LancelotMarti** [dscc-admin-ch/vllm#7]
Depends on #5

**Comment by Jono711** [comment]
Attendre réponse de Frédéric

**Comment by Jono711** [comment]
Create a helm with mostly default values and create a catalog afterwards

**Comment by Jono711** [comment]
Project name shouldn't be 'just' vllm ?

**Comment by Jono711** [comment]
Info on volumes: https://www.kubermatic.com/blog/keeping-the-state-of-apps-1-introduction-to-volume-and-volumemounts/

**Comment by Jono711** [comment]
vLLM deployment with volumes: https://medium.com/@55_learning/deploy-large-language-model-llm-with-vllm-on-k8s-6378be632b54

**Comment by Jono711** [comment]
How to add a locally trained model: https://github.com/vllm-project/vllm/issues/1131

**Comment by Jono711** [comment]
How to mount a local directory (doesn't work right now): https://julien-chen.medium.com/k8s-how-to-mount-local-directory-persistent-volume-to-kubernetes-pods-of-docker-desktop-for-mac-b72f3ca6b0dd
